service: climate-ml

provider:
  name: aws
  runtime: python2.7
  stage: dev
  environment:
    openweather_key: e98f6025fdfa352100ef5350a5aa98e8
    db_username: ${env:db_username}
    db_pass: ${env:db_pass}

  package:
    include:
      - countries_lat_lon.py

  iamRoleStatements:
    -   Effect: Allow
        Action:
          - s3:PutObject
        Resource: "arn:aws:s3:::climate.ml/*"

functions:
  climate-ml:
    handler: lambda_function.main
    events:
      - schedule: rate(2 hours)


plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
